### PR TITLE
kubernetes, docker, CI/CD

### PR DESCRIPTION
**Pull request by OriHoch**
* corresponding kubernetes helm chart - https://github.com/Midburn/midburn-k8s/tree/master/charts-external/dreams#dreams-helm-sub-chart

the chart is deployed on staging environment and has continuous deployment - once you merge this PR it will work, please check the .travis.yml for the environment matrix - regarding which branch deploys to which environment

needs some more work to expose publically, add DB web UI, import data from production, test etc.. documented what needs to be done in Midburn/midburn-k8s#13

### CODE REVIEW

**Comment by enoodle** [comment]
@OriHoch Can you squash the travis so we can merge this nicely?

**Comment by OriHoch** [comment]
you can squash and merge from github 
image

**Comment by enoodle** [comment]
@OriHoch It says that all the commits will be merged into one, I was hoping to keep the logical ones and get read of the `.travis` fixes.

**Comment by OriHoch** [comment]
thanks, deployment after the merge looks good

https://travis-ci.org/Midburn/Dreams/builds/339218003
this is the relevant log of the deployment to staging - 
https://travis-ci.org/Midburn/Dreams/jobs/339218004#L1166

**Pull request merged**
